### ISSUE TITLE
Page editor

### ISSUE THREAD

**Issue by walliski** [Teknologforeningen/tf-info#5]
Possibility to make a page based on markdown or a WYSIWYG editor

**Comment by oehnstro** [comment]
WYSIWYG is a definite no. A markdown based editor might be possible, but I think most of the time it would be easier to allow users to upload images or create custom html pages. Using existing websites is already build in (though not documented yet).

**Comment by walliski** [comment]
Using a markdown editor would have the advantage that all text on all pages shown would use the same style, compared to people making own images/custom HTML pages that is difficult to do.

**Comment by oehnstro** [comment]
Good point. Markdown or custom image sounds good.

**Comment by walliski** [comment]
This issue could be a part of #34, or more easily done after it.
